WEB_APP/Controllers/ClaimController.cs
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc;
using WEB_API.Models;
using WEB_APP.Models;
using System.Text;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc.Rendering;
using Azure;
using System.Net;
using System.Net.Http.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Security.Claims;

namespace WEB_APP.Controllers
{
    public class ClaimController : Controller
    {
        private string apiUrl;

        public ClaimController()
        {
            var MyConfig = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            apiUrl = MyConfig.GetValue<string>("AppSettings:apiUrl")+"ClaimApi/";
        }

        public async Task<ActionResult> Index(string? Status = null, DateTime? DateFrom = null, DateTime? DateTo = null)
        {

            var currentAction = this.ControllerContext.RouteData.Values["action"].ToString();

            ClaimViewModel viewModel = new ClaimViewModel();
            viewModel.Status = Status;
            viewModel.DateFrom = DateFrom;
            viewModel.DateTo = DateTo;

            using (var client = new HttpClient()) {
                client.BaseAddress = new Uri(this.apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync(String.Format(currentAction+ "?status={0}&DateFrom={1}&DateTo={2}", Status, DateFrom, DateTo));
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<ClaimModel>>();
                    readTask.Wait();

                    viewModel.list_ = (List<ClaimModel>)readTask.Result;

                }
                else //web api sent error response 
                {
                    //log response status here...
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }

                // Fetch list of SelectListItems for statuses
                var claimStatusesUrl = "ClaimStatuses";
                if (Status != null)
                {
                    claimStatusesUrl += $"?Status={Uri.EscapeDataString(Status)}";
                }

                var claimStatusesResponse = await client.GetAsync(claimStatusesUrl);
                if (claimStatusesResponse.IsSuccessStatusCode)
                {
                    var statuses = await claimStatusesResponse.Content.ReadAsAsync<List<SelectListItem>>();
                    viewModel.Statuses = statuses;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to retrieve claim statuses from API.");
                }

                //responseTask = client.GetAsync(String.Format("ClaimStatuses?Status={0}", Status));
                //responseTask.Wait();
                //result = responseTask.Result;
                //if (result.IsSuccessStatusCode)
                //{
                //    var readTask = result.Content.ReadAsAsync<IList<SelectListItem>>();
                //    readTask.Wait();

                //    viewModel.Statuses = (List<SelectListItem>)readTask.Result;

                //}
                //else //web api sent error response 
                //{
                //    //log response status here...
                //    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                //}
            }

            return View(viewModel);
        }


        [HttpGet]
        public IActionResult New()
        {
            EditClaimModel model = new EditClaimModel ();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(this.apiUrl);

                var responseTask = client.GetAsync(String.Format("ClaimStatuses?Status={0}", model.Status));
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<SelectListItem>>();
                    readTask.Wait();

                    model.Statuses = (List<SelectListItem>)readTask.Result;

                }

                else //web api sent error response 
                {
                    //log response status here...
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }

            }

            return View(model); 
        }

        [HttpPost]
        public async Task<ActionResult> New(EditClaimModel model)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(this.apiUrl);
                //HTTP POST
                if (ModelState.IsValid)
                {
                    ClaimModel claimModel = new ClaimModel();
                    claimModel.PatientName = model.PatientName;
                    claimModel.DateOfService = model.DateOfService;
                    claimModel.MedicalProvider = model.MedicalProvider;
                    claimModel.Diagnosis = model.Diagnosis;
                    claimModel.ClaimAmount = model.ClaimAmount;

                    claimModel.Status = model.Status;
                    try
                    {
                        string json = JsonConvert.SerializeObject(claimModel);
                        var content = new StringContent(json, Encoding.UTF8, "application/json");

                        HttpResponseMessage response = await client.PostAsync("https://localhost:7017/api/ClaimApi/add", content);

                        if (response.IsSuccessStatusCode)
                        {
                            return Redirect("https://localhost:7298/Claim/Index");
                        }
                        else
                        {
                            // Handle unsuccessful response (optional)
                            ModelState.AddModelError(string.Empty, "Failed to update claim.");
                        }

                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError(string.Empty, "Error: " + ex.Message);
                    }
                }

                //fetch statuses
                var responseTask = client.GetAsync(String.Format("ClaimStatuses?Status={0}", model.Status));
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<SelectListItem>>();
                    readTask.Wait();

                    model.Statuses = (List<SelectListItem>)readTask.Result;

                }
                else //web api sent error response 
                {
                    //log response status here...
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult View(int Id)
        {
            ClaimModel model = new ClaimModel();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(this.apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync(String.Format("GetById?Id={0}", Id));
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ClaimModel>();
                    readTask.Wait();
                    model = (ClaimModel)readTask.Result;

                }
                else //web api sent error response 
                {
                    //log response status here...
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int Id) {
            EditClaimModel model = new EditClaimModel();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(this.apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync(String.Format("GetById?Id={0}", Id));
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ClaimModel>();
                    readTask.Wait();
                    var claimModel = (ClaimModel)readTask.Result;

                    model.ClaimId = claimModel.ClaimId;
                    model.PatientName = claimModel.PatientName;
                    model.DateOfService = claimModel.DateOfService;
                    model.MedicalProvider = claimModel.MedicalProvider;
                    model.Diagnosis = claimModel.Diagnosis;
                    model.ClaimAmount = claimModel.ClaimAmount;
                    model.Status = claimModel.Status;
                }

                responseTask = client.GetAsync(String.Format("ClaimStatuses?Status={0}", model.Status));
                responseTask.Wait();
                result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<SelectListItem>>();
                    readTask.Wait();

                    model.Statuses = (List<SelectListItem>)readTask.Result;

                }

                else //web api sent error response 
                {

WEB_APP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_APP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_APP.styles.css" asp-append-version="true" />

    @*     
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

    <!-- Include Moment.js and Bootstrap DateTimePicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" /> 
    *@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WEB_APP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Claim" asp-action="">Claim</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WEB_APP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>